### ISSUE TITLE
Have problem reproducing bulk RNA seq result

### ISSUE THREAD

**Issue by wangxinge** [statOmics/tradeSeqPaper#1]
Hi there,

I'm running the code for bulk RNA seq time course data. But my gamList is not a large list composed by each gene. So I cannot not proceed to look at fit for each gene.

## fit GAM
gamList <- fitGAM(counts, pseudotime=time, cellWeights=weights, nknots=6)

May I ask do you know how to fix it?

**Comment by koenvandenberge** [comment]
We have changed the default behavior from `tradeSeq` to return a `SingleCellExperiment` object rather than a list of models, since it's more efficient.
You can go back to having a list of models by setting `sce=FALSE` in the `fitGAM` function.

**Comment by wangxinge** [comment]
Thank you! It fixed my problem.
